Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

